blank_issues_enabled: false
contact_links:
  - name: Readme
    url: https://github.com/cryptohub-digital/core-units#readme
    about: Read more about the code
  - name: CLI tool
    url: https://github.com/cryptohub-digital/core-units#cli
    about: Get information about the Command-line interface
