name: Build extension
on:
  workflow_run:
    workflows: [Tests]
    branches: [master]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install builder 🔧
        run: npm i web-ext
      - name: Copy files 🗂
        run: npm run copy
      - name: Build extension 🧩
        run: npm run extension
